package net.minestom.server;

/**
 * AUTOGENERATED by ConstantsGenerator
 */
interface MinecraftConstants {
    String VERSION_NAME = "1.17.1";

    int PROTOCOL_VERSION = 756;

    int DATA_VERSION = 2730;

    int RESOURCE_PACK_VERSION = 7;

    int DATA_PACK_VERSION = 7;
}
